language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: compartetusideas-nodejs
  api_key:
    secure: Z8345leWW40IKtkcOGHgMFD17tMSDjqCUwagImfcVqvb9BGtYzD7LgXgsPPyHbfNG8RtgC2boEqgwww5Ut8x2PV7K1eK+h2uSmwxgf0qqliA4KE/4k5160MmySkKAulCiTk5j3H5Xw/sMQkMIrqoYBerNP8/FQik9zbdOHoyZskxuKDhflHbmYQSbrY0KNbsNDE2vke6hQOuHWR0Gxdc/on56TwmGUf5ZYXJt/LoRdsgcLz2XBfwulwzUuruHGRgeKddHWCUTzOgLonp9G+C2xblwk4yLKkJ1M7mh0GEX1+BpTcnDmtMZP3D2c9QSVx1DmniGMthlYhsDUtLbSvJPX75qzQUpIWY3IUZvN51iaXwVQ46qz+S2SCnvEoOl2lZ3n8ofdaFobMD2gXRXHqWpL/UHi7YOzTKUiR/BisguilyB0D0h4JhzH+mrfBpdq2BsF36QkzWtE/K46cDwh7MEvDwNkG300FWuVAWuFdMCaEuzQD7e7N9uUtLOWh3pI5739XO22pY/ut/O6DypyzTrTkZaKcj+PMniie+AUWKDZHrKFV+NYtQh0YRdO+dqe1Go0H4YdEvEo5l9bIQr3WvNstJWAMdzQ5zi41L3js+ntJ+lwTL0PYRGB7iV5P/xBuJsUA/1UnptsdroqIyJTXXiWXZK4R86Wqrm6qLJFTsIZ8=
