language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: compartetusideas-nodejs
  api_key:
    secure: u6qmwBuEFige8yMb04AF3zMfqX8iAqjL7eICSaan2Z93HScAXd7YIC5+7prOyc6vb9Rn695FVtKIExDa4XdaJ6jpYiQLiaKiJWPn0zSG7ZHMd1y4MdFiEBNn8EmOcmOUulyNkUOTdUwfiJbSOeIN3wJsHqtBr9zxquyU3YqxFQJ3sE37rnpj9hgAHgZoWe0C6SGegYBChZIYhI1pCOk7U8QQGbyIOiLRny9ksmeTcMnRaR4YSSC3skKEeaUCkWU+2TJiNBAyqULWlbNWBDdKbCMKOtIgQF/z8kdAo7M5NkIDaeW0aPyBoNlvfQdKVsCkQXOwy6NkTzwVtfi4qm4K9ty7hOMEEmQ2w5+o1QCZSR710wrwOxbm1cA8VDaCrBvgrv2EepxC184PChk2e0O3jmKn6lANqzsaeQjIusvzaAtrhayX6Rcaa/nS4TZA1GsAOPGriBKs+/u+XjDYVx0eNza6kOH/UGfZt2p49d9NhET664SIwQO/GQHA6nmtsbktAr4GqsOiYqqTPdS3qkTSXzz3vSgNpPv7AuBKuxknYaxImr/7so4rrs5UOjgAyVE9g7lGPBz6ArRpbLsXMPgELRldm2n62Mb2XKCUT46gL/3k4uYAM3MlG+x7SxerYGwf0P+a/g/p007nOtLawTMUqN6ppXv0prXHdeBJJWltUvg=
