language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: compartetusideas-nodejs
  api_key:
    secure: gJFVR2YiTGxWbxAlNZKWAoymFPH4TnT86kJHVJTSEGcVfperQ8MqGR3R7d7c8vIdD/SYxzHVCfdf4P1kTgt2cPWp6tZ4/G0PVnLnZBn0zOFQCylsN8cF9yyACzDYHUud0wRphCm5MbHxKcFrZOI0MEnBu1yT0O8RIy4NREd539Pl7uD0GLSLHlBdcSbp3X8xF8pzk7mN3Unp3b7fHtn0M3nWQ74C7jtDQZ/vRQfuX5ZrIP2MwJN+KOESR6vzpXceE0f1cy/ndLv1ZgrGsxsy59ZNQBe5DvdngxHp/YZA4Ix2m6MJVWneCoWNjYgUV4Ozn51EJzuLiz5VEFpWQKOy92qr2WrApFf3Lk5PA24G24pYpweSVOiIPajnLC8K2lrtKy7GySjjd671GcNCGBtNlDyJHZlyN/khWUnMWDoiXRBBl6vZw9ENRwZqhQnxyXBBRWG/Ywo9pbCD5tXnShgqHbe6zaE9ZanEsO8tTQHkvlMaaFLibZWWoa8GbFfYF3qT0N7rHuG2heoQMJV5oNmvK9WmpY/Mymfe7+dsbN0na/0wDIjS9vzVhpsgwF/ADXg4LOSZWwGLEqt6WP5vsq7d5Dz2YcxDFM2nE00Pg5CaQ03x79RxW2ent+kseLsA2YLZ2NGe1nGFt0nR0Ko5Cfu3OvWnB/tfKObM000S95UWBAY=
